GET http://localhost:5076/games

###
GET http://localhost:5076/games/4

###
POST http://localhost:5076/games
Content-Type: application/json

{
    "name": "Double Dragon",
    "genreId": 1,
    "price": 9.99,
    "releaseDate": "2011-11-18"
}

###
PUT http://localhost:5076/games/1
Content-Type: application/json

{
    "id": 2,
    "name": "Double Dragon",
    "genreId": 1,
    "price": 9.99,
    "releaseDate": "1987-06-01"
}

###
DELETE http://localhost:5076/games/4
