GET http://localhost:5076/games

###
GET http://localhost:5076/games/2

###
POST http://localhost:5076/games
Content-Type: application/json

{
    "name": "Tekken 4",
    "genreId": 1,
    "price": 15.99,
    "releaseDate": "2001-07-01"
}

###
PUT http://localhost:5076/games/2
Content-Type: application/json

{
    "id": 2,
    "name": "Minecraft",
    "genreId": 5,
    "price": 49.99,
    "releaseDate": "2015-06-01"
}

###
DELETE http://localhost:5076/games/2
